spring.application.name=sbapp10

#server.details
server.port =8889

#dbDetails
spring.datasource.url =jdbc:mysql://localhost:3306/hostels_db
spring.datasource.Driver-class-name =com.mysql.cj.jdbc.Driver
spring.datasource.username =root
spring.datasource.password =root

#jpa Details
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql =true